[package]
name = "skytable"
version = "0.1.0"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
edition = "2018"
readme = "README.md"
description = "Official Rust client driver for Skytable"
license = "Apache-2.0"
documentation = "https://docs.rs/skytable"
repository = "https://github.com/skytable/client-rust"
categories = []
keywords = ["skytable", "driver", "client", "database", "nosql"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
tokio = {version = "1.5.0", features = ["net", "io-util", "io-std"]}
lazy_static = "1.4.0"

[dev-dependencies]
tokio = {version="1.5.0", features=["rt", "macros"]}