[package]
name = "aio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skytable = { version="*", features=["async"], default-features=false }
tokio = { version="*", features=["full"] }
