name: Publish crate

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
